/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.text.DateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.User;


public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    private JPanel BottomPanel;
    private File selectedImageFile;
    public FormPanel(JPanel inputPanel) {
        initComponents();
        this.BottomPanel=inputPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        FormPanel = new javax.swing.JPanel();
        PatientRegistrationForm = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        AgeLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        TypeLabel = new javax.swing.JLabel();
        GenderLabel = new javax.swing.JLabel();
        FirstNameText = new javax.swing.JTextField();
        LastNameText = new javax.swing.JTextField();
        AgeText = new javax.swing.JTextField();
        EmailText = new javax.swing.JTextField();
        TypeCombo = new javax.swing.JComboBox<>();
        MaleButton = new javax.swing.JRadioButton();
        FemaleButton = new javax.swing.JRadioButton();
        OtherButton = new javax.swing.JRadioButton();
        MessageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessageArea = new javax.swing.JTextArea();
        photoLabel = new javax.swing.JLabel();
        UploadButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        FirstNameError = new javax.swing.JLabel();
        LastNameError = new javax.swing.JLabel();
        AgeError = new javax.swing.JLabel();
        EmailError = new javax.swing.JLabel();
        PathLabel = new javax.swing.JLabel();
        DateLabel = new javax.swing.JLabel();

        FormPanel.setBackground(new java.awt.Color(204, 153, 255));

        PatientRegistrationForm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        PatientRegistrationForm.setText("PATIENT REGISTRATION FORM");

        FirstNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        FirstNameLabel.setText("FIRST NAME:");

        LastNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LastNameLabel.setText("LAST NAME:");

        AgeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgeLabel.setText("AGE:");

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emailLabel.setText("EMAIL:");

        TypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TypeLabel.setText("TYPE:");

        GenderLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GenderLabel.setText("GENDER:");

        FirstNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FirstNameTextKeyReleased(evt);
            }
        });

        LastNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LastNameTextKeyReleased(evt);
            }
        });

        AgeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTextActionPerformed(evt);
            }
        });
        AgeText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AgeTextKeyReleased(evt);
            }
        });

        EmailText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                EmailTextKeyReleased(evt);
            }
        });

        TypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PATIENT", "GUEST" }));
        TypeCombo.setSelectedIndex(-1);

        GenderGroup.add(MaleButton);
        MaleButton.setText("MALE");

        GenderGroup.add(FemaleButton);
        FemaleButton.setText("FEMALE");

        GenderGroup.add(OtherButton);
        OtherButton.setText("PREFER NOT TO SAY");

        MessageLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        MessageLabel.setText("MESSAGE:");

        MessageArea.setColumns(20);
        MessageArea.setRows(5);
        jScrollPane1.setViewportView(MessageArea);

        photoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        photoLabel.setText("PHOTO");

        UploadButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UploadButton.setText("UPLOAD BUTTON");
        UploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UploadButtonActionPerformed(evt);
            }
        });

        SubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SubmitButton.setText("SUBMIT");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        FirstNameError.setForeground(new java.awt.Color(255, 51, 51));

        LastNameError.setForeground(new java.awt.Color(255, 0, 0));

        AgeError.setForeground(new java.awt.Color(255, 0, 51));

        EmailError.setForeground(new java.awt.Color(255, 0, 0));

        DateLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DateLabel.setText("DOB:");

        javax.swing.GroupLayout FormPanelLayout = new javax.swing.GroupLayout(FormPanel);
        FormPanel.setLayout(FormPanelLayout);
        FormPanelLayout.setHorizontalGroup(
            FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(MessageLabel)
                            .addComponent(LastNameLabel)
                            .addComponent(FirstNameLabel)
                            .addComponent(AgeLabel)
                            .addComponent(emailLabel)
                            .addComponent(TypeLabel)
                            .addComponent(GenderLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(FormPanelLayout.createSequentialGroup()
                                        .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(EmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(MaleButton)
                                    .addComponent(FemaleButton)
                                    .addComponent(OtherButton)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(AgeText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                    .addComponent(LastNameText)
                                    .addComponent(FirstNameText))
                                .addGap(18, 18, 18)
                                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LastNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AgeError, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PathLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(FormPanelLayout.createSequentialGroup()
                                .addComponent(photoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UploadButton)
                                .addGap(141, 141, 141)
                                .addComponent(DateLabel)))
                        .addContainerGap(441, Short.MAX_VALUE))))
            .addGroup(FormPanelLayout.createSequentialGroup()
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(PatientRegistrationForm))
                    .addGroup(FormPanelLayout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(SubmitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FormPanelLayout.setVerticalGroup(
            FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PatientRegistrationForm)
                .addGap(18, 18, 18)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNameError))
                .addGap(18, 18, 18)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LastNameError))
                .addGap(18, 18, 18)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgeLabel)
                    .addComponent(AgeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgeError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(EmailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailError))
                .addGap(18, 18, 18)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeLabel)
                    .addComponent(TypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenderLabel)
                    .addComponent(MaleButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FemaleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OtherButton)
                .addGap(18, 18, 18)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MessageLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FormPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoLabel)
                    .addComponent(UploadButton)
                    .addComponent(DateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PathLabel)
                .addGap(45, 45, 45)
                .addComponent(SubmitButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AgeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTextActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // TODO add your handling code here:
        User newUser=new User();
        newUser.setFirstname(FirstNameText.getText());
        newUser.setLastname(LastNameText.getText());
        newUser.setAge(AgeText.getText());
        newUser.setEmail(EmailText.getText());
        newUser.setType(TypeCombo.getSelectedItem().toString());
        newUser.setMessage(MessageArea.getText());
        newUser.setFilename(filename);
        Date date = jDateChooser1.getDate();
        String strDate = DateFormat.getDateInstance().format(date);
        newUser.setDate(strDate);
        if (MaleButton.isSelected() == true) {
            newUser.setGender("Male");
        } else if (FemaleButton.isSelected() == true) {
            newUser.setGender("Female");
        } else {
            newUser.setGender("Prefer not to say");
        }
         
        ViewPanel newViewPanel=new ViewPanel(newUser);
        BottomPanel.add(newViewPanel);
        CardLayout layout=(CardLayout) BottomPanel.getLayout();
        layout.next(BottomPanel);
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void FirstNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FirstNameTextKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(FirstNameText.getText());
        if(!match.matches()){
            FirstNameError.setText("Enter only Alphabets");
        }else{
             FirstNameError.setText("");
        }
    }//GEN-LAST:event_FirstNameTextKeyReleased

    private void LastNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LastNameTextKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z]{0,30}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(LastNameText.getText());
        if(!match.matches()){
            LastNameError.setText("Enter only Alphabets");
        }else{
             LastNameError.setText("");
        }
    }//GEN-LAST:event_LastNameTextKeyReleased

    private void AgeTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeTextKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[0-9]{0,3}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(AgeText.getText());
        if(!match.matches()){
            AgeError.setText("Enter only Numbers");
        }else{
             AgeError.setText("");
        }
    }//GEN-LAST:event_AgeTextKeyReleased

    private void EmailTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_EmailTextKeyReleased
        // TODO add your handling code here:
        String PATTERN="^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match =patt.matcher(EmailText.getText());
        if(!match.matches()){
            EmailError.setText("Enter valid EmailID");
        }
        else{
             EmailError.setText("");
        }
    }//GEN-LAST:event_EmailTextKeyReleased

    private void UploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UploadButtonActionPerformed
        // TODO add your handling code here:
         // JFileChooser fileChooser = new JFileChooser();
       JFileChooser chooser=new JFileChooser();
       //chooser.showOpenDialog(null);
       FileNameExtensionFilter fnef= new FileNameExtensionFilter("IMAGE","png","jpg","jpeg");
       chooser.addChoosableFileFilter(fnef);
       int returnValue = chooser.showOpenDialog(null);
       if (returnValue == JFileChooser.APPROVE_OPTION) {
           selectedImageFile = chooser.getSelectedFile();
          
             
              // BufferedImage img = ImageIO.read(selectedImageFile);
              // ImageIcon icon = new ImageIcon(img);
              File selectedImageFile=chooser.getSelectedFile();
               filename = selectedImageFile.getAbsolutePath();
               PathLabel.setText(filename);
       
           
       
    }
        
    }//GEN-LAST:event_UploadButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgeError;
    private javax.swing.JLabel AgeLabel;
    private javax.swing.JTextField AgeText;
    private javax.swing.JLabel DateLabel;
    private javax.swing.JLabel EmailError;
    private javax.swing.JTextField EmailText;
    private javax.swing.JRadioButton FemaleButton;
    private javax.swing.JLabel FirstNameError;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameText;
    private javax.swing.JPanel FormPanel;
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JLabel GenderLabel;
    private javax.swing.JLabel LastNameError;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JRadioButton MaleButton;
    private javax.swing.JTextArea MessageArea;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JRadioButton OtherButton;
    private javax.swing.JLabel PathLabel;
    private javax.swing.JLabel PatientRegistrationForm;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JComboBox<String> TypeCombo;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JButton UploadButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel photoLabel;
    // End of variables declaration//GEN-END:variables
String filename;
}
